name: 'PHP CodeSniffer Check'
description: 'PHPCS checker'
author: 'Kaspars Zarinovs, Team RH Fitness'
inputs:
  phpcs_path:
    description: 'Path to phpcs binary'
    required: false
    default: 'phpcs'
runs:
  using: 'docker'
  image: 'Dockerfile'
